// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_ale_numeric_breaks
NumericVector cpp_ale_numeric_breaks(NumericVector x, int n_intervals);
RcppExport SEXP _xplaineff_cpp_ale_numeric_breaks(SEXP xSEXP, SEXP n_intervalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_intervals(n_intervalsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ale_numeric_breaks(x, n_intervals));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ale_interval_index
IntegerVector cpp_ale_interval_index(NumericVector x, NumericVector breaks);
RcppExport SEXP _xplaineff_cpp_ale_interval_index(SEXP xSEXP, SEXP breaksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type breaks(breaksSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ale_interval_index(x, breaks));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ale_interval_aggregate
List cpp_ale_interval_aggregate(NumericVector d_l, IntegerVector interval_index);
RcppExport SEXP _xplaineff_cpp_ale_interval_aggregate(SEXP d_lSEXP, SEXP interval_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d_l(d_lSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type interval_index(interval_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ale_interval_aggregate(d_l, interval_index));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ale_numeric_finalize
List cpp_ale_numeric_finalize(NumericVector preds_lower, NumericVector preds_upper, IntegerVector interval_index);
RcppExport SEXP _xplaineff_cpp_ale_numeric_finalize(SEXP preds_lowerSEXP, SEXP preds_upperSEXP, SEXP interval_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type preds_lower(preds_lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type preds_upper(preds_upperSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type interval_index(interval_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ale_numeric_finalize(preds_lower, preds_upper, interval_index));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ale_numeric_effect_table
List cpp_ale_numeric_effect_table(NumericVector feat_val, NumericVector x_left, NumericVector x_right, IntegerVector interval_index, NumericVector preds_lower, NumericVector preds_upper);
RcppExport SEXP _xplaineff_cpp_ale_numeric_effect_table(SEXP feat_valSEXP, SEXP x_leftSEXP, SEXP x_rightSEXP, SEXP interval_indexSEXP, SEXP preds_lowerSEXP, SEXP preds_upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type feat_val(feat_valSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_left(x_leftSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_right(x_rightSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type interval_index(interval_indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type preds_lower(preds_lowerSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type preds_upper(preds_upperSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ale_numeric_effect_table(feat_val, x_left, x_right, interval_index, preds_lower, preds_upper));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ale_categorical_finalize
List cpp_ale_categorical_finalize(IntegerVector levels_id, NumericVector y_hat_plus, NumericVector y_hat_neg);
RcppExport SEXP _xplaineff_cpp_ale_categorical_finalize(SEXP levels_idSEXP, SEXP y_hat_plusSEXP, SEXP y_hat_negSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type levels_id(levels_idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_hat_plus(y_hat_plusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_hat_neg(y_hat_negSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ale_categorical_finalize(levels_id, y_hat_plus, y_hat_neg));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ale_categorical_effect_table
List cpp_ale_categorical_effect_table(IntegerVector feat_val, IntegerVector x_left, IntegerVector x_right, IntegerVector interval_index, NumericVector y_hat_plus, NumericVector y_hat_neg);
RcppExport SEXP _xplaineff_cpp_ale_categorical_effect_table(SEXP feat_valSEXP, SEXP x_leftSEXP, SEXP x_rightSEXP, SEXP interval_indexSEXP, SEXP y_hat_plusSEXP, SEXP y_hat_negSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type feat_val(feat_valSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x_left(x_leftSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x_right(x_rightSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type interval_index(interval_indexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_hat_plus(y_hat_plusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_hat_neg(y_hat_negSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ale_categorical_effect_table(feat_val, x_left, x_right, interval_index, y_hat_plus, y_hat_neg));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ale_numeric_prepare
List cpp_ale_numeric_prepare(NumericVector x, int n_intervals);
RcppExport SEXP _xplaineff_cpp_ale_numeric_prepare(SEXP xSEXP, SEXP n_intervalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type n_intervals(n_intervalsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ale_numeric_prepare(x, n_intervals));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ale_categorical_prepare
List cpp_ale_categorical_prepare(IntegerVector levels_id, int n_levels);
RcppExport SEXP _xplaineff_cpp_ale_categorical_prepare(SEXP levels_idSEXP, SEXP n_levelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type levels_id(levels_idSEXP);
    Rcpp::traits::input_parameter< int >::type n_levels(n_levelsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ale_categorical_prepare(levels_id, n_levels));
    return rcpp_result_gen;
END_RCPP
}
// ale_sweep_cpp
List ale_sweep_cpp(IntegerVector ord_idx, NumericMatrix d_l_mat, IntegerMatrix interval_idx_mat, IntegerVector offsets, NumericVector tot_n, NumericVector tot_s1, NumericVector tot_s2, NumericVector r_risks, LogicalVector is_cand, int min_node_size, int split_feat_j, NumericVector z_sorted, int n_obs);
RcppExport SEXP _xplaineff_ale_sweep_cpp(SEXP ord_idxSEXP, SEXP d_l_matSEXP, SEXP interval_idx_matSEXP, SEXP offsetsSEXP, SEXP tot_nSEXP, SEXP tot_s1SEXP, SEXP tot_s2SEXP, SEXP r_risksSEXP, SEXP is_candSEXP, SEXP min_node_sizeSEXP, SEXP split_feat_jSEXP, SEXP z_sortedSEXP, SEXP n_obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type ord_idx(ord_idxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type d_l_mat(d_l_matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type interval_idx_mat(interval_idx_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tot_n(tot_nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tot_s1(tot_s1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tot_s2(tot_s2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r_risks(r_risksSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type is_cand(is_candSEXP);
    Rcpp::traits::input_parameter< int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type split_feat_j(split_feat_jSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type z_sorted(z_sortedSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    rcpp_result_gen = Rcpp::wrap(ale_sweep_cpp(ord_idx, d_l_mat, interval_idx_mat, offsets, tot_n, tot_s1, tot_s2, r_risks, is_cand, min_node_size, split_feat_j, z_sorted, n_obs));
    return rcpp_result_gen;
END_RCPP
}
// calculate_ale_heterogeneity_single_cpp
double calculate_ale_heterogeneity_single_cpp(NumericVector d_l, IntegerVector interval_index);
RcppExport SEXP _xplaineff_calculate_ale_heterogeneity_single_cpp(SEXP d_lSEXP, SEXP interval_indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d_l(d_lSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type interval_index(interval_indexSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_ale_heterogeneity_single_cpp(d_l, interval_index));
    return rcpp_result_gen;
END_RCPP
}
// calculate_ale_heterogeneity_list_cpp
List calculate_ale_heterogeneity_list_cpp(List Y);
RcppExport SEXP _xplaineff_calculate_ale_heterogeneity_list_cpp(SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_ale_heterogeneity_list_cpp(Y));
    return rcpp_result_gen;
END_RCPP
}
// node_heterogeneity_cpp
NumericVector node_heterogeneity_cpp(List Y);
RcppExport SEXP _xplaineff_node_heterogeneity_cpp(SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(node_heterogeneity_cpp(Y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_pd_stack_newdata
Rcpp::List cpp_pd_stack_newdata(Rcpp::List data_cols, int feature_index, SEXP grid);
RcppExport SEXP _xplaineff_cpp_pd_stack_newdata(SEXP data_colsSEXP, SEXP feature_indexSEXP, SEXP gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data_cols(data_colsSEXP);
    Rcpp::traits::input_parameter< int >::type feature_index(feature_indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type grid(gridSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_pd_stack_newdata(data_cols, feature_index, grid));
    return rcpp_result_gen;
END_RCPP
}
// re_mean_center_ice_cpp
List re_mean_center_ice_cpp(List Y, List grid, IntegerVector idx);
RcppExport SEXP _xplaineff_re_mean_center_ice_cpp(SEXP YSEXP, SEXP gridSEXP, SEXP idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< List >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx(idxSEXP);
    rcpp_result_gen = Rcpp::wrap(re_mean_center_ice_cpp(Y, grid, idx));
    return rcpp_result_gen;
END_RCPP
}
// search_best_split_cpp
DataFrame search_best_split_cpp(DataFrame Z, List Y, int min_node_size, Nullable<int> n_quantiles);
RcppExport SEXP _xplaineff_search_best_split_cpp(SEXP ZSEXP, SEXP YSEXP, SEXP min_node_sizeSEXP, SEXP n_quantilesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< List >::type Y(YSEXP);
    Rcpp::traits::input_parameter< int >::type min_node_size(min_node_sizeSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type n_quantiles(n_quantilesSEXP);
    rcpp_result_gen = Rcpp::wrap(search_best_split_cpp(Z, Y, min_node_size, n_quantiles));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xplaineff_cpp_ale_numeric_breaks", (DL_FUNC) &_xplaineff_cpp_ale_numeric_breaks, 2},
    {"_xplaineff_cpp_ale_interval_index", (DL_FUNC) &_xplaineff_cpp_ale_interval_index, 2},
    {"_xplaineff_cpp_ale_interval_aggregate", (DL_FUNC) &_xplaineff_cpp_ale_interval_aggregate, 2},
    {"_xplaineff_cpp_ale_numeric_finalize", (DL_FUNC) &_xplaineff_cpp_ale_numeric_finalize, 3},
    {"_xplaineff_cpp_ale_numeric_effect_table", (DL_FUNC) &_xplaineff_cpp_ale_numeric_effect_table, 6},
    {"_xplaineff_cpp_ale_categorical_finalize", (DL_FUNC) &_xplaineff_cpp_ale_categorical_finalize, 3},
    {"_xplaineff_cpp_ale_categorical_effect_table", (DL_FUNC) &_xplaineff_cpp_ale_categorical_effect_table, 6},
    {"_xplaineff_cpp_ale_numeric_prepare", (DL_FUNC) &_xplaineff_cpp_ale_numeric_prepare, 2},
    {"_xplaineff_cpp_ale_categorical_prepare", (DL_FUNC) &_xplaineff_cpp_ale_categorical_prepare, 2},
    {"_xplaineff_ale_sweep_cpp", (DL_FUNC) &_xplaineff_ale_sweep_cpp, 13},
    {"_xplaineff_calculate_ale_heterogeneity_single_cpp", (DL_FUNC) &_xplaineff_calculate_ale_heterogeneity_single_cpp, 2},
    {"_xplaineff_calculate_ale_heterogeneity_list_cpp", (DL_FUNC) &_xplaineff_calculate_ale_heterogeneity_list_cpp, 1},
    {"_xplaineff_node_heterogeneity_cpp", (DL_FUNC) &_xplaineff_node_heterogeneity_cpp, 1},
    {"_xplaineff_cpp_pd_stack_newdata", (DL_FUNC) &_xplaineff_cpp_pd_stack_newdata, 3},
    {"_xplaineff_re_mean_center_ice_cpp", (DL_FUNC) &_xplaineff_re_mean_center_ice_cpp, 3},
    {"_xplaineff_search_best_split_cpp", (DL_FUNC) &_xplaineff_search_best_split_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_xplaineff(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
